from utils.arguments.DatasetsArguments import DatasetsArguments
from utils.arguments.ModelArguments import ModelArguments
from utils.arguments.TNTTrainingArguments import TNTTrainingArguments
from utils.arguments.InferenceArguments import InferenceArguments